name: Continuous integration
on:
  push:
    branches: ['**']
    tags: [v*]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: unit tests
        run: sbt +test
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags, required for sbt-dynver
      - uses: olafurpg/setup-scala@v12
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: $
          PGP_SECRET: $
          SONATYPE_PASSWORD: $
          SONATYPE_USERNAME: $